import { CommissionSellerType, ShippingPackageTierCode } from "@prisma/client";

export type SeedCommissionProfile = {
  key: string;
  label: string;
  sellerType: CommissionSellerType;
  minAmount: number;
  maxAmount: number | null;
  buyerCommissionRate: number;
  buyerCommissionMin: number;
  buyerCommissionMax: number;
  buyerServiceFeeRate: number;
  buyerServiceFeeMin: number;
  buyerServiceFeeMax: number;
  sellerCommissionRate: number;
  sellerCommissionMin: number;
  sellerCommissionMax: number;
  sellerPlatformFeeRate: number;
  sellerPlatformFeeMin: number;
  sellerPlatformFeeMax: number;
  tradeFeeSellerAmount: number;
  tradeFeeBuyerAmount: number;
  shippingShares: Record<ShippingPackageTierCode, number>;
};

/**
 * Strict model kategori jokerine izin vermediği için bu on profil her aktif
 * kategoriye ayrı somut kural satırları olarak açılır. Bir kategoride tam olarak
 * on bitişik kural vardır: FREE/BASIC için üçer, PREMIUM/BUSINESS için ikişer.
 */
export const SEED_COMMISSION_PROFILES: SeedCommissionProfile[] = [
  {
    key: "free-entry",
    label: "Free Baslangic",
    sellerType: CommissionSellerType.FREE,
    minAmount: 0,
    maxAmount: 1_000,
    buyerCommissionRate: 0.5,
    buyerCommissionMin: 1,
    buyerCommissionMax: 10,
    buyerServiceFeeRate: 1,
    buyerServiceFeeMin: 2,
    buyerServiceFeeMax: 20,
    sellerCommissionRate: 6,
    sellerCommissionMin: 3,
    sellerCommissionMax: 60,
    sellerPlatformFeeRate: 1,
    sellerPlatformFeeMin: 1,
    sellerPlatformFeeMax: 15,
    tradeFeeSellerAmount: 20,
    tradeFeeBuyerAmount: 20,
    shippingShares: { small: 100, medium: 90, large: 80 },
  },
  {
    key: "free-standard",
    label: "Free Standart",
    sellerType: CommissionSellerType.FREE,
    minAmount: 1_000,
    maxAmount: 5_000,
    buyerCommissionRate: 0.4,
    buyerCommissionMin: 4,
    buyerCommissionMax: 20,
    buyerServiceFeeRate: 0.8,
    buyerServiceFeeMin: 8,
    buyerServiceFeeMax: 40,
    sellerCommissionRate: 5.5,
    sellerCommissionMin: 55,
    sellerCommissionMax: 275,
    sellerPlatformFeeRate: 0.8,
    sellerPlatformFeeMin: 8,
    sellerPlatformFeeMax: 40,
    tradeFeeSellerAmount: 25,
    tradeFeeBuyerAmount: 25,
    shippingShares: { small: 90, medium: 80, large: 70 },
  },
  {
    key: "free-high",
    label: "Free Yuksek Deger",
    sellerType: CommissionSellerType.FREE,
    minAmount: 5_000,
    maxAmount: null,
    buyerCommissionRate: 0.25,
    buyerCommissionMin: 12.5,
    buyerCommissionMax: 75,
    buyerServiceFeeRate: 0.5,
    buyerServiceFeeMin: 25,
    buyerServiceFeeMax: 150,
    sellerCommissionRate: 5,
    sellerCommissionMin: 250,
    sellerCommissionMax: 1_000,
    sellerPlatformFeeRate: 0.5,
    sellerPlatformFeeMin: 25,
    sellerPlatformFeeMax: 100,
    tradeFeeSellerAmount: 30,
    tradeFeeBuyerAmount: 30,
    shippingShares: { small: 80, medium: 70, large: 60 },
  },
  {
    key: "basic-entry",
    label: "Basic Baslangic",
    sellerType: CommissionSellerType.BASIC,
    minAmount: 0,
    maxAmount: 1_000,
    buyerCommissionRate: 0.4,
    buyerCommissionMin: 1,
    buyerCommissionMax: 8,
    buyerServiceFeeRate: 0.8,
    buyerServiceFeeMin: 2,
    buyerServiceFeeMax: 16,
    sellerCommissionRate: 5,
    sellerCommissionMin: 2.5,
    sellerCommissionMax: 50,
    sellerPlatformFeeRate: 0.75,
    sellerPlatformFeeMin: 1,
    sellerPlatformFeeMax: 12,
    tradeFeeSellerAmount: 18,
    tradeFeeBuyerAmount: 18,
    shippingShares: { small: 90, medium: 80, large: 70 },
  },
  {
    key: "basic-standard",
    label: "Basic Standart",
    sellerType: CommissionSellerType.BASIC,
    minAmount: 1_000,
    maxAmount: 5_000,
    buyerCommissionRate: 0.3,
    buyerCommissionMin: 3,
    buyerCommissionMax: 15,
    buyerServiceFeeRate: 0.6,
    buyerServiceFeeMin: 6,
    buyerServiceFeeMax: 30,
    sellerCommissionRate: 4.5,
    sellerCommissionMin: 45,
    sellerCommissionMax: 225,
    sellerPlatformFeeRate: 0.6,
    sellerPlatformFeeMin: 6,
    sellerPlatformFeeMax: 30,
    tradeFeeSellerAmount: 22,
    tradeFeeBuyerAmount: 22,
    shippingShares: { small: 80, medium: 70, large: 60 },
  },
  {
    key: "basic-high",
    label: "Basic Yuksek Deger",
    sellerType: CommissionSellerType.BASIC,
    minAmount: 5_000,
    maxAmount: null,
    buyerCommissionRate: 0.2,
    buyerCommissionMin: 10,
    buyerCommissionMax: 60,
    buyerServiceFeeRate: 0.4,
    buyerServiceFeeMin: 20,
    buyerServiceFeeMax: 120,
    sellerCommissionRate: 4,
    sellerCommissionMin: 200,
    sellerCommissionMax: 800,
    sellerPlatformFeeRate: 0.4,
    sellerPlatformFeeMin: 20,
    sellerPlatformFeeMax: 80,
    tradeFeeSellerAmount: 27,
    tradeFeeBuyerAmount: 27,
    shippingShares: { small: 70, medium: 60, large: 50 },
  },
  {
    key: "premium-standard",
    label: "Premium Standart",
    sellerType: CommissionSellerType.PREMIUM,
    minAmount: 0,
    maxAmount: 2_500,
    buyerCommissionRate: 0.25,
    buyerCommissionMin: 1,
    buyerCommissionMax: 12.5,
    buyerServiceFeeRate: 0.5,
    buyerServiceFeeMin: 1.5,
    buyerServiceFeeMax: 25,
    sellerCommissionRate: 3.5,
    sellerCommissionMin: 2,
    sellerCommissionMax: 87.5,
    sellerPlatformFeeRate: 0.4,
    sellerPlatformFeeMin: 1,
    sellerPlatformFeeMax: 10,
    tradeFeeSellerAmount: 15,
    tradeFeeBuyerAmount: 15,
    shippingShares: { small: 70, medium: 60, large: 50 },
  },
  {
    key: "premium-high",
    label: "Premium Yuksek Deger",
    sellerType: CommissionSellerType.PREMIUM,
    minAmount: 2_500,
    maxAmount: null,
    buyerCommissionRate: 0.15,
    buyerCommissionMin: 3.75,
    buyerCommissionMax: 45,
    buyerServiceFeeRate: 0.3,
    buyerServiceFeeMin: 7.5,
    buyerServiceFeeMax: 90,
    sellerCommissionRate: 3,
    sellerCommissionMin: 75,
    sellerCommissionMax: 600,
    sellerPlatformFeeRate: 0.3,
    sellerPlatformFeeMin: 7.5,
    sellerPlatformFeeMax: 60,
    tradeFeeSellerAmount: 20,
    tradeFeeBuyerAmount: 20,
    shippingShares: { small: 60, medium: 50, large: 40 },
  },
  {
    key: "business-standard",
    label: "Isletme Standart",
    sellerType: CommissionSellerType.BUSINESS,
    minAmount: 0,
    maxAmount: 5_000,
    buyerCommissionRate: 0.15,
    buyerCommissionMin: 1,
    buyerCommissionMax: 15,
    buyerServiceFeeRate: 0.3,
    buyerServiceFeeMin: 1.5,
    buyerServiceFeeMax: 30,
    sellerCommissionRate: 2.5,
    sellerCommissionMin: 2,
    sellerCommissionMax: 125,
    sellerPlatformFeeRate: 0.25,
    sellerPlatformFeeMin: 1,
    sellerPlatformFeeMax: 12.5,
    tradeFeeSellerAmount: 12,
    tradeFeeBuyerAmount: 12,
    shippingShares: { small: 50, medium: 40, large: 30 },
  },
  {
    key: "business-high",
    label: "Isletme Yuksek Deger",
    sellerType: CommissionSellerType.BUSINESS,
    minAmount: 5_000,
    maxAmount: null,
    buyerCommissionRate: 0.1,
    buyerCommissionMin: 5,
    buyerCommissionMax: 30,
    buyerServiceFeeRate: 0.2,
    buyerServiceFeeMin: 10,
    buyerServiceFeeMax: 60,
    sellerCommissionRate: 2,
    sellerCommissionMin: 100,
    sellerCommissionMax: 400,
    sellerPlatformFeeRate: 0.2,
    sellerPlatformFeeMin: 10,
    sellerPlatformFeeMax: 40,
    tradeFeeSellerAmount: 16,
    tradeFeeBuyerAmount: 16,
    shippingShares: { small: 40, medium: 30, large: 20 },
  },
];

export const SEED_SHIPPING_TIERS = [
  {
    code: ShippingPackageTierCode.small,
    label: "Kucuk Paket",
    minDesi: 0,
    maxDesi: 2,
    amount: 100,
    sampleWidth: 20,
    sampleHeight: 10,
    sampleLength: 25,
    sortOrder: 0,
  },
  {
    code: ShippingPackageTierCode.medium,
    label: "Orta Paket",
    minDesi: 2,
    maxDesi: 5,
    amount: 130,
    sampleWidth: 35,
    sampleHeight: 20,
    sampleLength: 45,
    sortOrder: 1,
  },
  {
    code: ShippingPackageTierCode.large,
    label: "Buyuk Paket",
    minDesi: 5,
    maxDesi: null,
    amount: 160,
    sampleWidth: 60,
    sampleHeight: 40,
    sampleLength: 70,
    sortOrder: 2,
  },
] as const;
